# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Adrien Bouttier
author: hibigbob
email: contact@adrienbouttier.com
description: > # this means to ignore newlines until "baseurl:"
    Développeur Fullstack (NodeJs/ReactJs/Symfony2) à Lyon depuis 9 ans.
    VIM addict, Bépo enthousiaste, en veille active sur des technos comme : NodeJs, ReactJs, VueJs, Angular, Go
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: hibigbob
github_username:  hibigbob

minima:
    date_format: "%d-%m-%Y"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
